spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:demo
    data-username: sa
    data-password:
  jpa:
    hibernate:
      ddl-auto: none
server:
  port: 8081