spring:
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    sql-script-encoding: UTF-8
  jpa:
    properties:
      hibernate.show_sql: true
    hibernate:
      ddl-auto: none